/**
 * TableEnum.java
 * Created at 2014-12-28
 * Created by 樊华伟
 * Copyright (C) 2014 mobilereal All rights reserved.
 */

package cn.com.mobilereal.common.dao;

/**
 * <p>ClassName: TableEnum</p>
 * <p>Description: 所有的数据库表</p>
 * <p>Author: 樊华伟</p>
 * <p>Date: 2014-12-28</p>
 */

public enum TableEnum {
	TC_AREA("TC_AREA"),
	TC_CODE_DETAIL("TC_CODE_DETAIL"),
	TC_CODE_LIST("TC_CODE_LIST"),
	TM_DEVICE("TM_DEVICE"),
	TM_SHORT_CUT("TM_SHORT_CUT"),
	TR_ROLE_BUTTON("TR_ROLE_BUTTON"),
	TR_ROLE_MENU("TR_ROLE_MENU"),
	TR_ROLE_SHORT_CUT("TR_ROLE_SHORT_CUT"),
	TR_USER_ROLE("TR_USER_ROLE"),
	TR_WORK_ERROR_CATEGORY("TR_WORK_ERROR_CATEGORY"),
	TS_APNS_MESSAGE("TS_APNS_MESSAGE"),
	TS_APNS_MESSAGE_RECEIVER("TS_APNS_MESSAGE_RECEIVER"),
	TS_ATTACHMENT("TS_ATTACHMENT"),
	TS_BAIDU_INFO("TS_BAIDU_INFO"),
	TS_DEPT("TS_DEPT"),
	TS_MENU_BUTTON("TS_MENU_BUTTON"),
	TS_MENU_FUNCTION("TS_MENU_FUNCTION"),
	TS_OPERATE_LOG("TS_OPERATE_LOG"),
	TS_OPERATE_LOG_MOBILE("TS_OPERATE_LOG_MOBILE"),
	TS_OPERATE_LOG_WEB("TS_OPERATE_LOG_WEB"),
	TS_ROLE("TS_ROLE"),
	TS_USER("TS_USER"),
	TS_WORK("TS_WORK"),
	TT_AGENT("TT_AGENT"),
	TT_CUSTOMER("TT_CUSTOMER"),
	TT_MACHINE("TT_MACHINE"),
	TT_MACHINE_BOX("TT_MACHINE_BOX"),
	TT_MACHINE_EXTEND("TT_MACHINE_EXTEND"),
	TT_MACHINE_RUN_STATE("TT_MACHINE_RUN_STATE"),
	TT_MACHINE_WARRANTY_DELAY("TT_MACHINE_WARRANTY_DELAY"),
	TT_OTHER_MACHINE("TT_OTHER_MACHINE"),
	TT_PART_BASE("TT_PART_BASE"),
	TT_PART_USAGE("TT_PART_USAGE"),
	TT_WORK_FLOW_ASSET("TT_WORK_FLOW_ASSET"),
	TT_WORK_ORDER("TT_WORK_ORDER"),
	TT_WORK_ORDER_FLOW("TT_WORK_ORDER_FLOW"),
	TT_WORK_REPORT("TT_WORK_REPORT");

	
	private String tableName;
	
	public String getTableName(){
		return tableName;
	}
	
	private TableEnum(String tname){
		tableName = tname;
	}	
}